module.exports = global.PDFlanguages = {
  rus: {
    h1: "BUDGET PROPOSAL",
    h2: "PREPARED FOR",
    h3: "PREPARED BY",
    p1: "What is Kickidler?",
    p2: "Our monitoring software allows you to see what your employees are doing, which sites and apps they are using. Kickidler automatically creates reports about the work of your employees all meanwhile taking care of managing any infractions via a system of smart violation filters. Our app offers your business a full suite of monitoring & managing solutions making your job as a manager easier and your team more productive.",
    p3: "Main Characteristics",
    p4: "   Smart and automatic reports",
    p5: "   Control of work violations",
    p6: "   Online monitoring",
    p7: "   Video recording of work activity",
    p8: "   Customizable work calendar",
    p9: "   Remote access to your employees’ PC",
    p10: "   And much more!",
    p11: "Components of Our Software Package",
    p12: " Grabber – Data collection software, installs in the computer(s) of the employee(s) to be monitored. Requires licensing in order to use freely.",
    p13: " Viewer – Monitoring software, to be installed in the computer(s) of the manager(s) responsible for monitoring and managing the employees.",
    p14: " Central Server – Central server is an API responsible for the communication in between the Grabber and the Viewer, this software is to be installed in the company server or on a computer, which satisfies the Technical Requirements.",
    p15: " Unlimited tech support & Updates – Our team will help you through the process of installing, setting up and maintaining our software package, as well as providing you with free updates and improvements.",
    p16: "Technical Requirements",
    p17: "For the monitoring of 100 employees with a recording speed of 60 frames per minute. We recomend:", //Work on the calculator
    p18: "1. HDD RAID 0 – 1.5 TB",
    p19: "2. RAM - 16 GB",
    p20: "3. CPU QUAD CORE 3 GHz",
    p21: "4. Local network speed over 100 Mbit/s",
    p22: "For more information please access:",
    p23: "https://www.kickidler.com/br/for-it/installation-instructions/system-requirements.html",
    t1: "Overview of the Budget Proposal",
    t2: "Product Name",
    t3: "Employee monitoring software - Kickidler",
    t4: "Type of the Product & Amount",
    t5: "Licensing of the software Grabber, ", //amount
    t5_1: [ "лицензия", "лицезии", "лицензий" ],
    t6: "Service Provider Company",
    t7: "IT Service Management LLC. Russia, Moscow, Str. Derbenevskaya Naberezhnaya, 11",
    t8: "Payment Type",
    t9: "License",
    t10: "Price in", //origin_currency
    t11: "Discount",
    t12: "Estimated Total in ", //client_currency*
    t13: "Virtual Price per License per Month", //**
    t14: "Paypal",
    t15: "Bank Invoice",
    t16: "Per Month",
    t17: "Per 3 Months",
    t18: "Per 3 Months",
    t19: "Per Year",
    t20: "Per 3 Years",
    t21: "Lifetime",
    d1: "%",
    d2: "Non applicable",
    t22: "*          Estimated Paypal transfer fee of 2.9%",
    t23: " - For more information please access: www.paypal.com/us/for-you/transfer-money/send-money/send-money-internationally",
    t24: "*          Estimated Bank Invoice transfer fee of 3.8%",
    t25: " - For more information please contact your bank",
    t26: "**         Virtual cost is estimated via the formula [Estimated Total]/[Amount]/[License Duration]",
    t27: " - Virtual cost serves as a reference value and may not be equal to the payment cost of the package",
    t28: "***        You can also pay for the service package via TransferWise",
    t29: " - For more information please access: https://transferwise.com/",
    t30: "To accept or to further discuss this budget proposal please contact the responsible Kickidler employee",
    t31: "Name",
    t32: "Email",
    t33: "Website",
    t34: "www.kickidler.com/",
    t35: "Telephone"
  },
  eng: {
    h1: "BUDGET PROPOSAL",
    h2: "PREPARED FOR",
    h3: "PREPARED BY",
    p1: "What is Kickidler?",
    p2: "Our monitoring software allows you to see what your employees are doing, which sites and apps they are using. Kickidler automatically creates reports about the work of your employees all meanwhile taking care of managing any infractions via a system of smart violation filters. Our app offers your business a full suite of monitoring & managing solutions making your job as a manager easier and your team more productive.",
    p3: "Main Characteristics",
    p4: "   Smart and automatic reports",
    p5: "   Control of work violations",
    p6: "   Online monitoring",
    p7: "   Video recording of work activity",
    p8: "   Customizable work calendar",
    p9: "   Remote access to your employees’ PC",
    p10: "   And much more!",
    p11: "Components of Our Software Package",
    p12: " Grabber – Data collection software, installs in the computer(s) of the employee(s) to be monitored. Requires licensing in order to use freely.",
    p13: " Viewer – Monitoring software, to be installed in the computer(s) of the manager(s) responsible for monitoring and managing the employees.",
    p14: " Central Server – Central server is an API responsible for the communication in between the Grabber and the Viewer, this software is to be installed in the company server or on a computer, which satisfies the Technical Requirements.",
    p15: " Unlimited tech support & Updates – Our team will help you through the process of installing, setting up and maintaining our software package, as well as providing you with free updates and improvements.",
    p16: "Technical Requirements",
    p17: "For the monitoring of 100 employees with a recording speed of 60 frames per minute. We recomend:", //Work on the calculator
    p18: "1. HDD RAID 0 – 1.5 TB",
    p19: "2. RAM - 16 GB",
    p20: "3. CPU QUAD CORE 3 GHz",
    p21: "4. Local network speed over 100 Mbit/s",
    p22: "For more information please access:",
    p23: "https://www.kickidler.com/br/for-it/installation-instructions/system-requirements.html",
    t1: "Overview of the Budget Proposal",
    t2: "Product Name",
    t3: "Employee monitoring software - Kickidler",
    t4: "Type of the Product & Amount",
    t5: "Licensing of the software Grabber, ", //amount
    t5_1: [ "license", "licenses" ],
    t6: "Service Provider Company",
    t7: "IT Service Management LLC. Russia, Moscow, Str. Derbenevskaya Naberezhnaya, 11",
    t8: "Payment Type",
    t9: "License",
    t10: "Price in", //origin_currency
    t11: "Discount",
    t12: "Estimated Total in ", //client_currency*
    t13: "Virtual Price per License per Month", //**
    t14: "Paypal",
    t15: "Bank Invoice",
    t16: "Per Month",
    t17: "Per 3 Months",
    t18: "Per 3 Months",
    t19: "Per Year",
    t20: "Per 3 Years",
    t21: "Lifetime",
    d1: "%",
    d2: "Non applicable",
    t22: "*          Estimated Paypal transfer fee of 2.9%",
    t23: " - For more information please access: www.paypal.com/us/for-you/transfer-money/send-money/send-money-internationally",
    t24: "*          Estimated Bank Invoice transfer fee of 3.8%",
    t25: " - For more information please contact your bank",
    t26: "**         Virtual cost is estimated via the formula [Estimated Total]/[Amount]/[License Duration]",
    t27: " - Virtual cost serves as a reference value and may not be equal to the payment cost of the package",
    t28: "***        You can also pay for the service package via TransferWise",
    t29: " - For more information please access: https://transferwise.com/",
    t30: "To accept or to further discuss this budget proposal please contact the responsible Kickidler employee",
    t31: "Name",
    t32: "Email",
    t33: "Website",
    t34: "www.kickidler.com/",
    t35: "Telephone"
  },
  por: {
    h1: "PROPOSTA DE ORÇAMENTO",
    h2: "PREPARADA PARA",
    h3: "PREPARADA POR",
    p1: "O que é a Kickidler?",
    p2: "Nosso programa de monitoramento permite ver o quê os seus funcionários estão fazendo, quais sites estão abrindo, quais programas estão usando. A Kickidler automaticamente gera relátorios inteligentes e sinaliza sobre qualquer infração das regras de trabalho. Facilitando a contabilização do tempo de trabalho e garantindo a eficácia e a segurança da sua empresa.",
    p3: "Principais Características",
    p4: "   Relatórios inteligentes",
    p5: "   Controle de infrações",
    p6: "   Monitoramento online",
    p7: "   Gravação em video do histórico de uso",
    p8: "   Calendário de trabalho customizável",
    p9: "   Acesso remoto ao PC dos seus funcionários",
    p10: "   E muito mais!",
    p11: "Componentes do Programa",
    p12: " Grabber – Software de coleta de dados, instalado no computador do(s) funcionário(s) a serem monitorados. Pode ser instalado tanto em modo secreto (invísivel) quanto não (visível). Necessita de licença para ser usado.",
    p13: " Viewer – Software de monitoramento de dados e controle de funcionários, instalado no computador do(s) funcionário(s) que estarão monitorando.",
    p14: " Servidor Central – Servidor responsável pelo armazenamento dos dados, pela comunicação entre o Viewer e o Grabber e a configuração dos mesmos. É instalado no servidor da empresa ou em um computador que satisfaça os Requisitos Técnicos.",
    p15: " Suporte técnico ilimitado – Nosso suporte cobre desde treinamento do uso da ferramenta a instalação e manutenção. Nós da Kickidler também oferecemos updates gratuitos do nosso serviço, tornando sua experiência ainda melhor.",
    p16: "Requisitos Técnicos",
    p17: "Para o monitoramento de 100 funcionários com uma velocidade de gravação de 60 capturas de tela por minuto. Recomendamos:", //Work on the calculator
    p18: "1. HDD RAID 0 – 1.5 TB",
    p19: "2. RAM - 16 GB",
    p20: "3. CPU QUAD CORE 3 GHz",
    p21: "4. Velocidade da rede local superior a 100 Mbit/s",
    p22: "Para mais informações por favor acesse",
    p23: "https://www.kickidler.com/br/for-it/installation-instructions/system-requirements.html",
    t1: "Overview do Orçamento",
    t2: "Nome do Produto",
    t3: "Software de monitoramento de funcionários - Kickidler",
    t4: "Tipo do produto e quantidade",
    t5: "Licensiamento do uso do software Grabber, ", //amount
    t5_1: [ "licença", "licenças" ],
    t6: "Empresa contratadora",
    t7: "IT Service Management LLC. Russia, Moscou, R. Derbenevskaya Naberezhnaya, 11",
    t8: "Modo de Pagamento",
    t9: "Duração da licença",
    t10: "Preço em", //origin_currency
    t11: "Desconto",
    t12: "Total Estimado em", //client_currency*
    t13: "Custo Virtual por Licença por Mês", //**
    t14: "Paypal",
    t15: "Invoice Bancârio",
    t16: "Mensal",
    t17: "Por 3 Meses",
    t18: "Por 6 Meses",
    t19: "Anual",
    t20: "Por 3 anos",
    t21: "Ilimitada",
    d1: "%",
    d2: "Não aplicavel",
    t22: "*          Taxa de transferência estimada do Paypal  =  2,9%",
    t23: " - Para mais informações acesse: https://www.paypal.com/pt/webapps/mpp/send-money-online",
    t24: "*          Taxa de transferência estimada do Invoice  =  3,8% (SWIFT 1% + emissão 2% + IOF 0,8%)",
    t25: " - Para mais informações por favor entre em contato com um representante do seu banco",
    t26: "**         Custo virtual estipulado através da formula [Total Estimado]/[Quantidade]/[Duração da licença]",
    t27: " - O custo virtual é um valor de referência e pode não condizer com o valor de pagamento do pacote de licenças",
    t28: "***        Você também pode fazer a transferência a partir do website Transferwise.com",
    t29: " - Para mais informações acesse: https://transferwise.com/br/",
    t30: "Para aceitar ou recusar a proposta por favor entre em contato com o representante Kickidler responsável",
    t31: "Nome",
    t32: "Email",
    t33: "Website",
    t34: "www.kickidler.com/br/",
    t35: "Número"
  },
  currency: {
    name: [ "RUB", "USD", "BRL", "EUR", "INR", "KZT", "BYR", "GBP", "CNY" ],
    symbol: [ "₽", "$", "R$", "€", "₹", "₸", "Br", "£", "¥"],
    prices_usd: [ 9.99, 24, 30, 50, 100, 170 ],
    prices_rub: [ 600, 1440, 1800, 3000, 6000, 10000 ],
    durations: [1, 3, 6, 12, 36, 120]
  },
  prices: {
    usd: { 1: 9.99, 3: 24, 6: 30, 12: 50, 36: 100, 0: 170 },
    rub: { 1: 600, 3: 1440, 6: 1800, 12: 3000, 36: 6000, 0: 10000 }
  },
  seller: {
    Кайо: [ "Caio Fleury", "Кай Флеури", "k.fleury@kickidler.com", "какой-то номер" ],
    Александр: [ "Alexander Minev", "Александр Минеев", "какая-то почта", "какой-то номер" ],
    Владмир: [ "Vladmir Starovoitov", "Владимир Старовойтов", "какая-то почта", "какой-то номер" ],
    Кирилл: [ "Kirill Martynov", "Кирилл Мартынов", "какая-то почта", "какой-то номер" ],
    Алехандро: [ "Alejandro Palunin", "Алехандро Палунин", "какая-то почта", "какой-то номер" ]
  }
};
